# Generated by Django 3.2.4 on 2021-06-16 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('comment', models.TextField()),
            ],
            options={
                'verbose_name': 'name',
                'verbose_name_plural': 'names',
            },
        ),
    ]
